# # Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
# #
# # The `spec.containers[0].args` contains the command run on the pod
# # The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# # That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# # 
# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     app: minio
#   name: minio
#   namespace: capture
# spec:
#   containers:
#   - name: minio
#     image: quay.io/minio/minio:latest
#     command:
#     - /bin/bash
#     - -c
#     args: 
#     - minio server /data --console-address :9090
#     env:
#     - name: MINIO_SERVER_URL
#       value: http://192.168.8.147:9090
#     - name: MINIO_BROWSER_REDIRECT_URL
#       value: http://192.168.8.147:9090
#     volumeMounts:
#     - mountPath: /data
#       name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
#   nodeSelector:
#     kubernetes.io/hostname: doit-4 # Specify a node label associated to the Worker Node on which you want to deploy the pod.
#   volumes:
#   - name: localvolume
#     hostPath: # MinIO generally recommends using locally-attached volumes
#       path: /mnt/minio/disk1/data # Specify a path to a local drive or volume on the Kubernetes worker node
#       type: DirectoryOrCreate # The path to the last directory must exist
# ---
# # https://kubernetes.io/docs/concepts/services-networking/service/
# apiVersion: v1
# kind: Service
# metadata:
#   name: minio
#   namespace: capture
# spec:
#   selector:
#     app: minio
#   type: ClusterIP
#   ports:
#   - name: minio
#     protocol: TCP
#     port: 5000
#     targetPort: 9090
# ---
